-- Drop all document tables
DROP TABLE IF EXISTS pcab_documents;
DROP TABLE IF EXISTS iso_certifying_body_documents;
DROP TABLE IF EXISTS dti_sec_cda_documents;
DROP TABLE IF EXISTS bir_documents;
DROP TABLE IF EXISTS lgu_documents;
DROP TABLE IF EXISTS sec_documents;
DROP TABLE IF EXISTS sss_documents;
DROP TABLE IF EXISTS philhealth_documents;
DROP TABLE IF EXISTS pag_ibig_fund_documents;
DROP TABLE IF EXISTS dole_accredited_training_centers_documents;
DROP TABLE IF EXISTS nbi_documents;
DROP TABLE IF EXISTS bir_accredited_cpa_documents;
DROP TABLE IF EXISTS company_appraiser_banks_documents;
DROP TABLE IF EXISTS bank_documents;
DROP TABLE IF EXISTS prc_documents;
DROP TABLE IF EXISTS dole_accredited_trainers_documents;
DROP TABLE IF EXISTS company_lto_suppliers_documents; 